name: Build OpenWrt

on: 
  watch:
    types: [started]
    
env:
  repo_url: https://github.com/immortalwrt/immortalwrt
  repo_branch: lede-17.01
  repo_os: openwrt
  config: .config
  diy_sh: diy.sh
  model: PSG1218
  TZ: Asia/Shanghai
  newpath: by-jczhl--.zip    #  by-jczhl.zip   by-jczhl-default-settings.zip
  newpack: true66
  ssh: true
  set: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 清理环境
      run: |
        docker rmi `docker images -q`
    - name: 配置环境
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
       
    - name: 获取源码&替换config
      run: |
        git clone --depth 1 $repo_url -b $repo_branch openwrt
        rm -rf $GITHUB_WORKSPACE/openwrt/.config
        mv $GITHUB_WORKSPACE/$config $GITHUB_WORKSPACE/openwrt/.config        

    - name: 解压by-jczhl.zip
      if: env.newpath == 'by-jczhl.zip' || env.newpath == 'by-jczhl-default-settings.zip'            
      run: |
        unzip $newpath -d openwrt/package      
           
    - name: 替换feeds.conf.default
      if: env.newpack == 'true'          
      run: |
        rm -rf $GITHUB_WORKSPACE/openwrt/.feeds.conf.default
        mv $GITHUB_WORKSPACE/feeds.conf.default $GITHUB_WORKSPACE/openwrt/feeds.conf.default        
        
    - name: 更新 feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: 安装 feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: 一系列可自定义配置
      if: env.set == 'true'      
      run: |
        chmod +x $diy_sh
        cd openwrt
        $GITHUB_WORKSPACE/$diy_sh              
      
    - name: 获取软件包
      run: |
        mkdir zhlhlf
        cd openwrt   
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: ssh连接
      if: env.ssh == 'true'            
      uses: P3TERX/ssh2actions@v1.0.0
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}      
        
    - name: 编译
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "::set-output name=status::success"
                            
    - name: zip 打包
      run: |
         rm -rf openwrt/bin/targets/*/*/packages 
         mv openwrt/.config zhlhlf/.config    
         zip -r $model-$repo_os-$repo_branch-by-jczhl.zip openwrt/bin/targets/*/*/*

    - name: 移动生成包至zhlhlf目录
      run: |
         mv $model-$repo_os-$repo_branch-by-jczhl.* zhlhlf

    - name: Upload bin directory
      uses: actions/upload-artifact@master
      with:
        name: openwrt-by-jczhl
        path: zhlhlf
        
      
